from selenium import webdriver
import time
driver = webdriver.Chrome()
driver.get("http://127.0.0.1:3000")
login = driver.find_element("id", 'loginforselenium').click()
time.sleep(3)
registration = driver.find_element("id", 'registrationforselenium').click()
time.sleep(3)
name = driver.find_element("id", 'nameforselenium').send_keys("Shiv")
time.sleep(3)
address = driver.find_element("id", 'addressforselenium').send_keys("valsad")
time.sleep(3)
city = driver.find_element("id", 'cityforselenium').send_keys("valsad")
time.sleep(3)
mobile_number = driver.find_element("id", 'mnoforselenium').send_keys("8934876454")
time.sleep(3)
email = driver.find_element("id", 'emailforselenium').send_keys("shiv123@gmail.com")
time.sleep(3)

password = driver.find_element("id", 'passwordforselenium').send_keys("1234")
time.sleep(3)
password = driver.find_element("id", 'passwordforselenium').click()
time.sleep(3)
register = driver.find_element("id", 'registerforselenium').click()
time.sleep(3)
login = driver.find_element("id", 'loginforselenium').click()
time.sleep(3)
email = driver.find_element("id", 'emailforselenium').send_keys("shiv123@gmail.com")
time.sleep(3)
password = driver.find_element("id", 'passforselenium').send_keys("1234")
time.sleep(3)
loginbutton = driver.find_element("id", 'loginbuttonforselenium').click()
time.sleep(3)
addtocart = driver.find_element("id", 'addtocartforselenium').click()
time.sleep(3)
addtocart1 = driver.find_element("id", 'addtocartforselenium1').click()
time.sleep(3)

viewcart = driver.find_element("id", 'viewcartforselenium').click()
time.sleep(3)
placeorder = driver.find_element("id", 'placeorderforselenium').click()
time.sleep(3)
address = driver.find_element("id", 'addressforselenium').send_keys("mograwadi")
time.sleep(3)
city = driver.find_element("id", 'cityforselenium').send_keys("valsad")
time.sleep(3)
mobile_number = driver.find_element("id", 'mnoforselenium').send_keys("6359826865")
time.sleep(3)
promocode = driver.find_element("id", 'promocodeforselenium').send_keys("DIS100")
time.sleep(3)
payment = driver.find_element("id", 'paymentforselenium').send_keys("COD")
time.sleep(2)
placedorder= driver.find_element("id", 'placedorderforselenium').click()
time.sleep(3)
logout= driver.find_element("id", 'logoutforselenium').click()
time.sleep(3)
time.sleep(15)